- name: copy aliases dotfile to user
  copy:
    src: .aliases
    dest: /home/{{ homeuser }}/.aliases
    owner: "{{ homeuser }}"
    group: "{{ homeuser }}"
    mode: 0644
- name: add .aliases to .bashrc
  lineinfile:
    path: /home/{{ homeuser }}/.bashrc
    line: 'source ~/.aliases'
- name: remove .emacs file
  ansible.builtin.file:
    path: /home/{{ homeuser }}/.emacs
    state: absent
- name: Create emacs.d directory
  ansible.builtin.file:
   path: /home/{{ homeuser }}/.emacs.d
   state: directory
   mode: '0755'
   owner: "{{ homeuser }}"
- name: copy init.el to .emacs.d directory
  copy:
    src: init.el
    dest: /home/{{ homeuser }}/.emacs.d
    owner: "{{ homeuser }}"
    group: "{{ homeuser }}"
    mode: 0644
- name: install packages
  package:
    name: "{{ packages }}"
  vars:
    packages:
    - firewalld
    - strawberry
    - audacious
    - audacious-plugins
    - mpv
    - vlc
    - neovim
    - podman
    - pandoc
    - remmina-plugin-rdp
    - remmina
    - pavucontrol
    - build-essential
    - qt5-qtsvg
    - make
    - ripgrep
    - zsh
    - golang
    - gopls
    - flatpak
    - qemu-system-x86
    - libvirt-daemon-system
    - libvirt-clients
    - qemu-system-modules-spice
    - virt-manager
    - gir1.2-spiceclientgtk-3.0
    - qemu-utils  
    - apt-listbugs
    - apt-listchanges
    - htop
    - chromium
    - webext-ublock-origin-chromium
    - apparmor-profiles-extra 
    - libspa-0.2-bluetooth
    - emacs-pgtk
    - git
- name: add flathub repo
  ansible.builtin.shell:
    cmd: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
- name: install flatpaks
  community.general.flatpak:
    name:
      - org.signal.Signal
      - com.discordapp.Discord
      - im.riot.Riot
      - org.telegram.desktop

#- name: copy custom sysctls
#  copy:
#    src: 99-default.conf
#    dest: /etc/sysctl.d/99-default.conf
#    owner: root
#    group: root
#    mode: 0644
#- name: copy custom blacklist modules
#  copy:
#    src: blacklist-items.conf
#    dest: /etc/modprobe.d/blacklist-items.conf
#    owner: root
#    group: root
#    mode: 0644
- name: Start firewalld service, if not started
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: yes
